- package.json
```
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "slackin"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! path /usr/local/lib/node_modules/slackin/bin/skackin
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/slackin/bin/skackin'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```
> Fix bin name

- Readme.md
It's only fair, given we advertise our own SVG button :)
> Use the SVG version of the Heroku button

- lib/badge.js
for some reason the `height` was set to `tw` (total width)
> svg height should be fixed, not equal to the width. fixes #24

- lib/slack.js
We thought it was weird to count the `slackbot` user. AFAIK that user is created by default and is always online, so it's pointless to count it.
Edit: Actually you probably don't want to count *any* sort of bots
> Don't count bots

- lib/slack-invite.js
When try to send invitation for single-channel guests, the correct parameter name is `channels`. I confirmed to actually send the request.
> Fix for single-channel guests invitation parameter name

- lib/slack-invite.js
I ran into this problem when trying to setup slackin for a group I'm a member of. When I deployed to Heroku and input my Slack subdomain and token, the success message appears ("Woot! Check your email!"), but no email arrives. I wasn't using single-channel mode. After debugging, I noticed that Slack returns a `200 OK` even if the account owning the API token is not an admin. This pull request returns an error in that case.
Note that I'm not a node dev, so I'm really not sure of the correct way to handle this. Let me know if there's a better way.
> Return an error when the token account is not an admin

- Dockerfile
- Procfile
This Dockerfile is the simplest way to get slackin running on Docker.
It's running here: https://slackin.octohost.io/
You can try the Docker build with:
```
docker pull octohost/slackin
docker run -d -P -e SLACK_CHANNEL=channel -e SLACK_SUBDOMAIN=subdomain -e SLACK_API_TOKEN=api-token-goes-here octohost/slackin:0.4.0
```
It will be listening on port 3000 - Docker will likely assign a random 49xxx port on the outside.
> Working Dockerfile and slightly adjusted Procfile.

- lib/badge.js
I noticed that sometimes™ the SVG badge wasn't rendered correctly. The SVG source made it very obvious what's wrong; [the `rw` variable](https://github.com/rauchg/slackin/blob/7e7f033ddb706056f4e1a66dce971afeda345b0e/lib/badge.js#L12) was `NaN`.
The only part that's not hardcoded is `width(value)`. The width function is quite simple, but value is a bit more "complicated":
If there are any `active` users, return a string showing "active/total" users, otherwise return the total users, or "-" of there's none.
So if there's 0 active users, but any total users, you'd end up calling `.length` on a Number (= `undefined`) and multiplicate that by 7 (= `NaN`).
-----
This tremendous PR should fix that
> Fix rendering bug (NaN) in SVG

- lib/index.js
- lib/slack-invite.js
- package.json
- test/index.js
- test/mocha.opts
- test/setup.js
- test/slack-invite.js
In trying to debug https://github.com/rauchg/slackin/issues/38, finally found that there was an error condition that wasn't being handled:
This PR:
* Handles a JSON response from the Slack invite API where the `ok` property is `false`
* Fixes passing of error messages to client
* Adds tests
/cc @ultrasaurus
> handle responses with `ok: false`

- lib/index.js
I've had problems with GitHub's [camo](https://github.com/atmos/camo) service aggressively caching badge.svg, preventing it from updating on README.md files.
Adding the `Cache-Control` header _should_ prevent GitHub from caching the badge.
See https://help.github.com/articles/why-do-my-images-have-strange-urls/#an-image-that-changed-recently-is-not-updating
> Add Cache-Control: no-cache to prevent GitHub camo caching

- lib/index.js
It would be better for SEO to have the title tag use the name variable and say for example "Join Project SAFE on Slack!" instead of "Join us on Slack!".
And we can put a Slack favicon instead of having nothing. I am not sure what image to use though.
In the commit, I put https://slack.global.ssl.fastly.net/272a/img/icons/favicon-32.png but it could also be https://slack.com/favicon.ico or something else.
Let me know what you think.
And thank you very much for making this :smile: !
I use it for https://slack.projectsafe.community.
> add Slack favicon and better title tag

- lib/slack.js
I'm eventually facing downtime issues with slackin service. Whenever I check the logs I see that are some requests being sent without the __channels__ attribute.
This pull request aims to do a safety fallback to an empty array in case the channels property is not in the request body.
> Added safety check for channels.

- Readme.md
Updated all http://slackin.yourhost.com references to http://slack.yourdomain.com to match the first example.
> Standardize use of example host

- Dockerfile
- Makefile
- Procfile
- Readme.md
- package.json
The Makefile in the project was pretty sparse. This commit turns it into a working makefile, where each prerequisite .js file in lib/ has a corresponding target in node/. As a result, invoking make will automatically determine which updated source files need to be transpiled again and incrementally do so. Similarly, files in lib/assets/ are incrementally copied to node/assets/. There is also a clean target to remove the node/ directory.
After cleaning up the make, I updated package.json and Procfile in order to tweak the heroku build/deploy process. Before, Heroku created node_modules and packaged them along with the source into a slug. This slug was deployed to a dyno, which would then invoke make and finally run the server. With this change, make happens during the build, so the built …
> Build process and Heroku improvements

- lib/index.js
- lib/slack-invite.js
- lib/splash.js
If you wind up back at the page to request an invite and input your address again, slack raises an error because you're already on the team. This adds a link below the signup button to take you back to Slack when you're already registered.
> Add already registered link

- lib/splash.js
Currently, no target set in the iframe can rain on some parades. This makes sure no rain happens, only _Slackshine_.
Couldn't resist..
> For new signin link, use target=_top so iframes work

- lib/assets/client.js
- lib/assets/iframe.js
- lib/splash.js
To host at mydomain.com/getslack, can't use absolute urls. Also,
socket.io needs to be initialized with the proper path.
Sample nginx config to host in a subfolder:
```
location /getslack/ {
proxy_pass http://localhost:3000/;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
```
> Allow hosting at a subfolder

- Readme.md
- bin/slackin
- package.json
As Heroku now requires popular free dynos to be down for 6 hours a day, moving from Heroku to OpenShift is probably something people want to do. This pull request adds support for OpenShift.
Uses https://github.com/bevry/hostenv to fetch the correct PORT and HOSTNAME variables for many different servers (including openshift). OpenShift requires explicit hostname on `.listen`.
Once merged, `rhc app deploy https://github.com/balupton/slackin.git#feature-openshift` should be changed to `rhc app deploy https://github.com/raunchg/slackin.git#master`
To get started with OpenShift today (before this pull request is merged), you can browse the instructions here: https://github.com/balupton/slackin/tree/feature-openshift#openshift
> Add openshift support

- bin/slackin
- lib/slack.js
Hi :wave:. I work for Slack and I'd like to make some updates to this app to improve performance and reduce the load on Slack's servers.
1. Commit https://github.com/rauchg/slackin/commit/27cc41bf214d31c88b46eb60b36a970930e59218 was intended to increase the default polling interval, but this value was always being overriden by `bin/slackin` so I updated it to 5s there as well
2. The `rtm.start` API call is quite expensive and returns a lot more data than Slackin uses. However until recently it was the only way for you to get bulk user presence data. I added a new optional arg to the `users.list` API called `presence` which, if passed, will include the presence data there. I've updated the code to poll this instead of `rtm.start` which will be much faster and lighter on the servers. The …
> Performance fixes

- lib/assets/client.js
This is necessary to get invite POSTing working when you host slackin in a subpath.
> Make invite post a relative path

- package.json
- test/index.js
The latest changes in v0.6.0 seemed to have caused the tests to fail, due to some missing Slack API mocks. This PR adds those mocks, and also upgrades nock to the latest version so that `.query()` can be used. Thanks for considering!
> Fix tests by adding missing mocks

- bin/slackin
No parameter was specified for the option which made it be broken. This
fixes `slackin --path "/slack/" org token`.
> Fix --path option parsing

- lib/index.js
This will get rid of the following errors being thrown by the slack object.
(node) warning: possible EventEmitter memory leak detected. 11 change listeners
added. Use emitter.setMaxListeners() to increase limit.
> Set maxListeners to 0 or user defined

- lib/assets/client.js
- lib/index.js
- lib/slack-invite.js
Would love to get a second set of eyes on this for review.
This adds onto #126, showing a new success message right before users get redirected to Slack.
> Add success message for already signed up users

- Readme.md
Updates the readme to use `require('slackin').default`
> Update readme for babel 6 change

- test/index.js
- test/mocha.opts
I'm relatively unacquainted with nodejs, but it appears that the module name for babel-register changed. Without my change, I see:
```
> slackin@0.8.2 test /home/jesse/workspace/slackin
> mocha
module.js:341
throw err;
^
Error: Cannot find module 'babel/register'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at /home/jesse/workspace/slackin/node_modules/mocha/bin/_mocha:300:3
at Array.forEach (native)
at Object.<anonymous> (/home/jesse/workspace/slackin/node_modules/mocha/bin/_mocha:294:19)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at …
```
> Fix mocha opts

- lib/assets/badge.js
- lib/assets/client.js
One thing missing from #126/#143, which intro'd the feature of
redirecting already-signed-up users to Slack, was support for the iframe
dialog that the "Realtime Badge" button thing pops up:
https://github.com/rauchg/slackin#realtime-badge
In simpler times this would've been a 4-character fix:
```diff
-        location.href = res.body.redirectUrl;
+        top.location.href = res.body.redirectUrl;
```
But nowadays people have futile "policies" trying to be "secure" about
their "content" and "sand" "box" "our" "i" "frames":
[![image](https://cloud.githubusercontent.com/assets/225809/13376193/930f93be-dd69-11e5-8476-13a3ab53531d.png)](http://output.jsbin.com/hagibe)
(You can test this by including `<meta http-equiv="Content-Security-Policy" content="sandbox allow-scripts …
> Fix redirecting already-registered users from iframe dialog

- lib/index.js
- lib/splash.js
Why was it excluded in #80? With the button that opens the iframe
dialog, there's no link to the landing page, which means with the button
there's no link at all to the actual Slack channel.
> Add "or sign in" link to iframe too

- Readme.md
Usage docs: https://developer.ibm.com/devops-services/2015/02/18/share-code-new-deploy-bluemix-button/
> Add IBM Bluemix Deploy badge

- lib/assets/client.js
- lib/splash.js
e35a05b9ca4b3754f814246542c87785af967650 introduced a problem -- the form sends `channel=null` when `SLACK_CHANNELS` contains only one entry, but [the relevant form handler](https://github.com/rauchg/slackin/blob/e3d31942c1c4c070b31f005e54addd46a644fac9/lib/index.js#L91) doesn't seem to cope with this scenario.
I figured the easiest way to fix this was to inject an `<input type="hidden">` in the single-channel case. This seems to work nicely, after a small tweak to the client-side form handler.
Fixes #77.
> Fix form when SLACK_CHANNELS contains only one entry

- lib/assets/badge.js
- lib/assets/iframe.js
- lib/assets/superagent.js
- lib/index.js
- lib/slack.js
Non-slackin code may postMessage() to the same window (in my case, a
Twitter button), and unlike slackin, may choose to send an object as a
message rather than a string. Unlike strings, not all objects have a
.substr() method, so slackin doing e.data.substr() throws an exception:
[![jsbin showing exception thrown by slackin after a postMessage()](https://git.io/v2N5t)](http://jsbin.com/gojudi/edit?html,output)
> Fix postMessage({}, '*') causes slackin to throw

- lib/assets/badge.js
- lib/index.js
- lib/splash.js
Passed along from `?large` to control the badge size, they now also
control the iframe and dialog size because after all, if you're on a
page with larger `font-size` that demands a larger badge, the small dialog
with small text is gonna look out of place:
The large badge is about 1.5x the size of the small badge (30px to 20px;
the other ratios aren't as exact), but I found that making the large
dialog 1.4x the size of the small dialog looked better than 1.5x
(that is, bumping the `em`/`rem` unit font size from 10px to 14px rather
than 15px), I think because at 1.5x the text in the dialog becomes bigger
than the text in the badge:
font-size: 14px
vs
font-size: 15px
--
See also https://github.com/rauchg/slackin/commit/6108430ed1698f4a0ea7d8bd966df3313582d667 for discussion of the `em`/`rem` …
> Fix ?large to also control size of dialog

- lib/assets/client.js
Introduced with the merge of https://github.com/rauchg/slackin/pull/152/ and the [release of v0.8.3](https://github.com/rauchg/slackin/compare/0.8.2...0.8.3).
**Fixes https://github.com/rauchg/slackin/issues/165**
The problem was if the `SLACK_CHANNELS` environment variable wasn't configured, then [no hidden form element](https://github.com/nickstenning/slackin/blob/ae93c74d32a1c1ddad79d96369394be3811c1608/lib/splash.js#L25) with the listed channels would be included. Therefore, our [`channel` variable would be `undefined`](https://github.com/nickstenning/slackin/blob/ae93c74d32a1c1ddad79d96369394be3811c1608/lib/assets/client.js#L22), and a direct access of the `value` property would throw an error.
Or perhaps there was something wrong on my end… just let me know if this PR isn't helpful …
> Fix TypeError regression when submitting form without optional SLACK_CHANNELS config

- Readme.md
The current heroku button doesn't work due to #164, #165 and #167
The current "doesn't work with free slacks" bug is still alive on 0.8.3 this lets idiot users like me use master until there's a tag for a branch that works.
> Change heroku deploy to master

- Dockerfile
Currently, the Procfile is configured to allow the Code of Conduct flag, but the Dockerfile is not. This causes issues with tools like Dokku that automatically use the Dockerfile over a Procfile. This update adds parity between the two.
> Update Dockerfile to Use the Code of Conduct Environment Variable

- Readme.md
As a new user of slackin I did not understand that I needed only a test token and that creating a whole OAuth 2 token was not needed and in fact would not work. This update the docs to be very clear that you should be using a test token with Slackin. Closes #178.
> Update docs with more clear token generation info

- README.md
- bin/slackin
- package.json
- Allows developers to use the `-h` flag for the hostname again (caused problems because it made the help pop up: https://github.com/rauchg/slackin/issues/206)
- Renamed the path to the build output directory (fixes https://github.com/rauchg/slackin/issues/203)
- Like suggested by @alexpls, the devDependency "babel-register" has been added. That means, [this PR](https://github.com/rauchg/slackin/pull/204) can be closed in favour of this one.
> Important bug fixes

- lib/index.js
- test/index.js
So you can setup LetsEncrypt certificates natively
> Supports letsencrypt challenges

- bin/slackin
- lib/index.js
Using `EMAIL_SLACK_LIST` to get an optional email list to filter user invites. This is useful for conferences and other spaces where you have a list of attendees and you don't want anybody else so get into slack.
This was used on slack.jsconf.co 💃
> Adding support to use environment variable to filter email inviting

- Dockerfile
This change was motivated by the following error encountered when running the image built using the pre-existing `octohost/nodejs`-based Dockerfile:
```
$ docker run --rm vdice/slackin:octohost-base sh -c './bin/slackin --version'
/srv/www/node_modules/args/dist/index.js:39
class Args {
^^^^^
SyntaxError: Unexpected reserved word
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/srv/www/bin/slackin:4:12)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
```
Whereas the image built off of the official …
> Switch to node:slim for Dockerfile base image

- lib/slack.js
My best guess here is that Slack's own API occasionally returns a members object that isn't what we expect it to be.
We tested with this defensive check and our slackin instance has been up for two weeks, a new record for us.
Fixes #201
> Fix for #201 by adding defensive statement

- lib/assets/badge.js
This fixes #182, where Firefox's flyout was positioned opposite scroll.
> Switch from pure document.body for badge flyout Firefox compatibility.

- lib/slack.js
e.g when `SLACK_SUBDOMAIN="<zeit-community>"` following error would show up:
```
/home/nowuser/src/dist/slack.js:53
(res.body.channels || []).forEach(function (channel) {
^
TypeError: Cannot read property 'body' of undefined
```
When really `err` is populated and contains real error.
> Show better error when slack subdomain incorrect

- lib/index.js
- lib/splash.js
Signups via the badge go down a slightly different path than signups via the main page (eventually ending up at https://example.com/iframe/dialog, https://github.com/rauchg/slackin/blob/master/lib/index.js#L248). Unfortunately this path doesn't pass `gcaptcha_sitekey` to `splash` (https://github.com/rauchg/slackin/blob/master/lib/splash.js#L3) which results in this error when you try to sign up:
```
Uncaught TypeError: Cannot read property 'value' of undefined
at HTMLBodyElement.<anonymous> (client.js:23)
```
The fix is to pass `gcaptcha_sitekey` which I have tested locally.
> Fix signup via badges

- readme.md
To get  a large badge, `?large`, not just `?`.
> Correct instructions for large badge

- package.json
Fixes https://github.com/rauchg/slackin/issues/328 ([for security purposes](https://snyk.io/test/npm/slackin/0.13.0)).
* `socket.io` : _1.4.8_ => ___2.0.3___ (or at least ___1.7.4___)
* `express` : _4.11.0_ => ___4.15.4___
* `superagent` : _0.21.0_ => ___3.6.0___
* `debug` : _2.1.1_ => ___3.0.1___
> fix: vulnerable packages

- readme.md
This update fixes the DevOps URL options on IBM Cloud platform. All `bluemix.net` URLs are being replaced to `cloud.ibm.com`. Also, the DevOps URL has changed with this the new IBM Cloud URL.
> Update the IBM Cloud deployment option
